const root=document.querySelector('#detailRoot');
const DATA_V='20';
const SITE_ROOT='https://whispermmepub.github.io/Whisper-Of-Words-App-Store/';
const libraryKey='wow-store-library-v1';
const slug=document.body.dataset.app||new URLSearchParams(location.search).get('app')||'wow-reader';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const posterShots={'wow-ocr':['apps/wow-ocr/screenshots/01-scan-ocr-export.svg','apps/wow-ocr/screenshots/02-fast-text-scanning.svg','apps/wow-ocr/screenshots/03-editable-text.svg','apps/wow-ocr/screenshots/04-cloud-ai-ocr.svg'],'wow-proof-reader':['apps/wow-proof-reader/screenshots/01-read-edit-perfect.svg','apps/wow-proof-reader/screenshots/02-inline-editing.svg','apps/wow-proof-reader/screenshots/03-find-replace.svg','apps/wow-proof-reader/screenshots/04-paragraph-tools.svg']};
function readLibrary(){try{return JSON.parse(localStorage.getItem(libraryKey)||'{}')||{}}catch{return {}}}
function writeLibrary(v){localStorage.setItem(libraryKey,JSON.stringify(v))}
function storedState(a){const item=readLibrary()[a.slug];if(!item)return 'install';if(item.version!==a.version)return 'update';return a.packageName?'open':'install'}
function rememberInstall(a){if(a.comingSoon||!a.apk)return;const lib=readLibrary();lib[a.slug]={version:a.version,at:Date.now(),name:a.name};writeLibrary(lib)}
function actionMarkup(a){if(a.comingSoon||!a.apk)return '<span class="install-action disabled">Coming Soon</span>';const state=storedState(a);if(state==='open')return `<a class="install-action" href="intent://#Intent;package=${encodeURIComponent(a.packageName)};end">Open</a>`;return `<a class="install-action" href="${esc(a.apk)}" download data-detail-install="${esc(a.slug)}">${state==='update'?'Update':'Install'}</a>`}
function previewMarkup(a,s,i){return `<img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" alt="${esc(a.name)} screenshot ${i+1}" data-preview-src="${esc(s)}">`}
function canonicalUrl(a){return `${SITE_ROOT}apps/${encodeURIComponent(a.slug)}/`}
function render(a){const shots=posterShots[a.slug]||a.screenshots||[],features=(a.features||[]).slice(0,8),changes=a.whatsNew||[];document.title=`${a.name} · Whisper Of Words App Store`;const canonical=document.querySelector('link[rel="canonical"]');if(canonical)canonical.href=canonicalUrl(a);root.innerHTML=`<section class="detail-hero"><img class="detail-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"><div class="detail-title"><h1>${esc(a.name)}</h1><div class="developer">${esc(a.developer)}</div><p>${esc(a.shortDescription)}</p></div></section><div class="detail-actions">${actionMarkup(a)}<button class="share-text" id="shareApp" type="button">Share</button></div><section class="detail-metrics"><div class="detail-metric"><strong>${esc(a.rating||'New')}</strong><span>Rating</span></div><div class="detail-metric"><strong>v${esc(a.version)}</strong><span>Version</span></div><div class="detail-metric"><strong>${a.comingSoon?'—':esc(a.size)}</strong><span>Size</span></div><div class="detail-metric"><strong>${esc(a.updated)}</strong><span>Updated</span></div></section>${shots.length?`<section class="detail-section"><h2>Screenshots</h2><div class="screenshot-strip">${shots.map((s,i)=>previewMarkup(a,s,i)).join('')}</div></section>`:''}<section class="detail-section"><h2>About</h2><p>${esc(a.description)}</p>${features.length?`<div class="feature-grid">${features.map(f=>`<div class="feature-card"><strong>${esc(f.title)}</strong><span>${esc(f.text)}</span></div>`).join('')}</div>`:''}</section><section class="detail-section"><h2>What's New</h2><div class="whats-new"><strong>Version ${esc(a.version)}</strong><ul>${changes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></section><section class="detail-section"><h2>Information</h2><div class="info-list"><div class="info-row"><strong>Developer</strong><span>${esc(a.developer)}</span></div><div class="info-row"><strong>Category</strong><span>${esc(a.category)}</span></div><div class="info-row"><strong>Android</strong><span>${esc(a.android)}</span></div><div class="info-row"><strong>Price</strong><span>${esc(a.price)}</span></div>${a.packageName?`<div class="info-row"><strong>Package</strong><span>${esc(a.packageName)}</span></div>`:''}</div></section>`;hydratePreviews();bindDetail(a)}
async function hydratePreviews(){const imgs=[...root.querySelectorAll('[data-preview-src]')];await Promise.all(imgs.map(async img=>{const path=img.dataset.previewSrc;try{let src=path;if(path.endsWith('.b64')){const r=await fetch(`${path}?v=${DATA_V}`,{cache:'no-store'});if(!r.ok)throw new Error();const b64=(await r.text()).trim().replace(/\s+/g,'');const mime=b64.startsWith('/9j/')?'image/jpeg':b64.startsWith('iVBOR')?'image/png':b64.startsWith('UklGR')?'image/webp':null;if(!mime)throw new Error();src=`data:${mime};base64,${b64}`}img.src=src;await img.decode();img.addEventListener('click',()=>openImage(src))}catch{img.remove()}}))}
function toast(msg){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)}el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
function bindDetail(a){document.querySelector('[data-detail-install]')?.addEventListener('click',()=>rememberInstall(a));document.querySelector('#shareApp')?.addEventListener('click',async()=>{const data={title:a.name,text:a.shortDescription,url:canonicalUrl(a)};try{if(navigator.share){await navigator.share(data);return}await navigator.clipboard.writeText(data.url);toast('App link copied')}catch{}})}
const dlg=document.querySelector('#imageDialog'),dlgImg=document.querySelector('#dialogImage');function openImage(src){if(!dlg||!dlgImg)return;dlgImg.src=src;dlg.showModal()}document.querySelector('#closeImage')?.addEventListener('click',()=>dlg.close());dlg?.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
Promise.all([fetch(`data/apps.json?v=${DATA_V}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`data/wow-note.json?v=${DATA_V}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()})]).then(([data,note])=>{const a=[...(data.apps||[]),note].find(x=>x.slug===slug);if(!a)throw new Error();render(a)}).catch(()=>root.innerHTML='<div class="loading-card">App not found.<br><br><a href="./#apps">Back to App Store</a></div>');