const root=document.querySelector('#detailRoot');const slug=new URLSearchParams(location.search).get('app')||'wow-reader';
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('wow-store-theme',t);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',t==='dark'?'#11161d':'#f7f8fa')}
setTheme(localStorage.getItem('wow-store-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));document.querySelector('#themeToggle')?.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('data/apps.json?v=6').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{const a=(d.apps||[]).find(x=>x.slug===slug);if(!a)throw new Error();document.title=`${a.name} · Whisper Of Words App Store`;render(a)}).catch(()=>root.innerHTML='<div class="loading-card">App not found.<br><br><a href="./">Back to Store</a></div>');
function render(a){const shots=a.screenshots||[],features=a.features||[],changes=a.whatsNew||[];root.innerHTML=`
<section class="app-head"><img class="detail-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"><div><h1>${esc(a.name)}</h1><div class="developer">${esc(a.developer)}</div><p>${esc(a.shortDescription)}</p><div class="head-actions"><a class="install-main" href="${esc(a.apk)}" download>GET</a><span class="version-note">v${esc(a.version)} · ${esc(a.size)}</span></div></div></section>
<section class="metrics">${[['Version',a.version],['Android',a.android],['Size',a.size],['Price',a.price]].map(([l,v])=>`<div class="metric"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('')}</section>
${shots.length?`<section class="detail-section"><h2>Preview</h2><div class="screenshot-strip">${shots.map((s,i)=>`<img src="${esc(s)}" alt="${esc(a.name)} screenshot ${i+1}" loading="lazy" data-full="${esc(s)}">`).join('')}</div></section>`:''}
<section class="detail-section"><h2>About</h2><p>${esc(a.description)}</p><div class="feature-list">${features.map(f=>`<div class="feature"><strong>${esc(f.title)}</strong><span>${esc(f.text)}</span></div>`).join('')}</div></section>
<section class="detail-section"><h2>What's New</h2><div class="release-card"><strong>Version ${esc(a.version)}</strong><ul>${changes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></section>
<section class="detail-section"><h2>Privacy</h2><div class="safety-card"><strong>${esc(a.safety?.title||'Local-first')}</strong><p>${esc(a.safety?.text||'')}</p></div></section>
<section class="detail-section"><h2>Information</h2><div class="info-list"><div class="info-row"><strong>Developer</strong><span>${esc(a.developer)}</span></div><div class="info-row"><strong>Category</strong><span>${esc(a.category)}</span></div><div class="info-row"><strong>Updated</strong><span>${esc(a.updated)}</span></div><div class="info-row"><strong>Package</strong><span>${esc(a.packageName)}</span></div><div class="info-row"><strong>Source</strong><span><a href="${esc(a.source)}" target="_blank" rel="noreferrer">View on GitHub</a></span></div></div></section>`;root.querySelectorAll('[data-full]').forEach(img=>img.addEventListener('click',()=>openImage(img.dataset.full)))}
const dlg=document.querySelector('#imageDialog'),dlgImg=document.querySelector('#dialogImage');function openImage(src){if(!dlg||!dlgImg)return;dlgImg.src=src;dlg.showModal()}document.querySelector('#closeImage')?.addEventListener('click',()=>dlg.close());dlg?.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});