const root=document.querySelector('#detailRoot');
const DATA_V='22';
const SITE_ROOT='https://whispermmepub.github.io/Whisper-Of-Words-App-Store/';
const REVIEW_REPO='whispermmepub/Whisper-Of-Words-App-Store';
const reviewIssues={'wow-reader':2,'wow-note':3,'wow-epub-maker':4,'wow-ocr':5,'wow-proof-reader':6};
const editorialSamples={
  'wow-reader':[
    {name:'Sample Reader A',initial:'A',rating:5,text:'EPUB library, Myanmar font controls and reading progress are the parts I would use most. The layout feels focused on reading instead of filling the screen with extra controls.'},
    {name:'Sample Reader B',initial:'B',rating:4,text:'The local-first approach is a strong point for a reading app. Highlights, notes and custom typography make the current feature set feel useful for long Myanmar books.'},
    {name:'Sample Reader C',initial:'C',rating:5,text:'The mix of EPUB/PDF support, author shelves and immersive reading is exactly the kind of simple offline reader workflow I look for.'}
  ],
  'wow-note':[
    {name:'Sample Notes User A',initial:'A',rating:5,text:'Fast notes, Myanmar Calendar and reader-first note viewing fit together well. The app feels aimed at people who write often but still want comfortable long-form reading.'},
    {name:'Sample Notes User B',initial:'B',rating:4,text:'Custom fonts, reminders, colors and private-note locking are a practical combination. I especially like that the note opens for reading first instead of immediately jumping into edit mode.'},
    {name:'Sample Notes User C',initial:'C',rating:5,text:'The local-first design and lightweight organization tools make this feel more useful than a basic text pad. Calendar notes are a nice touch for Myanmar users.'}
  ],
  'wow-epub-maker':[
    {name:'Store Preview A',initial:'A',rating:5,text:'The preview direction is promising: DOCX to EPUB on-device, document privacy, build progress and the ability to open the EPUB immediately after creation.'},
    {name:'Store Preview B',initial:'B',rating:4,text:'If the release preserves useful Word structure as shown in the preview, this could be a very convenient phone-based EPUB workflow.'},
    {name:'Store Preview C',initial:'C',rating:5,text:'Offline conversion is the feature that stands out most. Looking forward to the release build, especially for Myanmar book-production work.'}
  ],
  'wow-ocr':[
    {name:'Store Preview A',initial:'A',rating:5,text:'The preview shows a complete document flow rather than OCR alone: scanning, cleanup, Myanmar text recognition, editing and export all in one place.'},
    {name:'Store Preview B',initial:'B',rating:4,text:'Offline Myanmar OCR plus optional Cloud and AI OCR gives this app a flexible direction. The text workspace and multi-page tools look especially useful.'},
    {name:'Store Preview C',initial:'C',rating:5,text:'I like the idea of keeping scans organized before exporting TXT, DOCX or PDF. Waiting for the APK release to try the full workflow.'}
  ],
  'wow-proof-reader':[
    {name:'Store Preview A',initial:'A',rating:5,text:'The reader-first proofreading concept looks strong. Editing paragraphs without leaving the reading flow should be useful for long DOCX manuscripts.'},
    {name:'Store Preview B',initial:'B',rating:4,text:'Find/replace, edited-place review, formatting controls and backups make the preview feel closer to a focused publishing tool than a simple document editor.'},
    {name:'Store Preview C',initial:'C',rating:5,text:'The Finish Proofing to EPUB pipeline is the feature I am most interested in. Looking forward to testing the release build when it becomes available.'}
  ]
};
const libraryKey='wow-store-library-v1';
const slug=document.body.dataset.app||new URLSearchParams(location.search).get('app')||'wow-reader';
if(!document.querySelector('link[data-review-styles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='reviews.css?v=22';l.dataset.reviewStyles='1';document.head.append(l)}
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const posterShots={'wow-ocr':['apps/wow-ocr/screenshots/01-scan-ocr-export.svg','apps/wow-ocr/screenshots/02-fast-text-scanning.svg','apps/wow-ocr/screenshots/03-editable-text.svg','apps/wow-ocr/screenshots/04-cloud-ai-ocr.svg'],'wow-proof-reader':['apps/wow-proof-reader/screenshots/01-read-edit-perfect.svg','apps/wow-proof-reader/screenshots/02-inline-editing.svg','apps/wow-proof-reader/screenshots/03-find-replace.svg','apps/wow-proof-reader/screenshots/04-paragraph-tools.svg']};
function readLibrary(){try{return JSON.parse(localStorage.getItem(libraryKey)||'{}')||{}}catch{return {}}}
function writeLibrary(v){localStorage.setItem(libraryKey,JSON.stringify(v))}
function storedState(a){const item=readLibrary()[a.slug];if(!item)return 'install';if(item.version!==a.version)return 'update';return a.packageName?'open':'install'}
function rememberInstall(a){if(a.comingSoon||!a.apk)return;const lib=readLibrary();lib[a.slug]={version:a.version,at:Date.now(),name:a.name};writeLibrary(lib)}
function actionMarkup(a){if(a.comingSoon||!a.apk)return '<span class="install-action disabled">Coming Soon</span>';const state=storedState(a);if(state==='open')return `<a class="install-action" href="intent://#Intent;package=${encodeURIComponent(a.packageName)};end">Open</a>`;return `<a class="install-action" href="${esc(a.apk)}" download data-detail-install="${esc(a.slug)}">${state==='update'?'Update':'Install'}</a>`}
function previewMarkup(a,s,i){return `<img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" alt="${esc(a.name)} screenshot ${i+1}" data-preview-src="${esc(s)}">`}
function canonicalUrl(a){return `${SITE_ROOT}apps/${encodeURIComponent(a.slug)}/`}
function stars(n){return '★★★★★'.slice(0,n)+'☆☆☆☆☆'.slice(0,5-n)}
function sampleCards(a){return (editorialSamples[a.slug]||[]).map(r=>`<article class="review-card sample-review"><div class="review-top"><div class="review-avatar sample-avatar">${esc(r.initial)}</div><div class="review-person"><strong>${esc(r.name)} <span class="review-badge">Store sample</span></strong><span class="review-date">Example review · not a real user account</span></div><span class="review-stars" aria-label="${r.rating} out of 5 stars">${stars(r.rating)}</span></div><p class="review-body">${esc(r.text)}</p></article>`).join('')}
function reviewMarkup(a){const issue=reviewIssues[a.slug];if(!issue)return '';const url=`https://github.com/${REVIEW_REPO}/issues/${issue}#new_comment_field`;return `<section class="reviews-section"><div class="reviews-head"><h2>Ratings & Reviews</h2><a class="write-review" href="${url}" target="_blank" rel="noopener">Write a Review</a></div><p class="review-note">Real public reviews appear first. The three cards marked “Store sample” are store-written examples, not real user accounts.</p><div id="reviewList" class="review-list"><div class="review-loading">Loading public reviews…</div></div><div class="sample-caption">Store sample reviews</div><div class="review-list sample-list">${sampleCards(a)}</div></section>`}
function render(a){const shots=posterShots[a.slug]||a.screenshots||[],features=(a.features||[]).slice(0,8),changes=a.whatsNew||[];document.title=`${a.name} · Whisper Of Words App Store`;const canonical=document.querySelector('link[rel="canonical"]');if(canonical)canonical.href=canonicalUrl(a);root.innerHTML=`<section class="detail-hero"><img class="detail-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"><div class="detail-title"><h1>${esc(a.name)}</h1><div class="developer">${esc(a.developer)}</div><p>${esc(a.shortDescription)}</p></div></section><div class="detail-actions">${actionMarkup(a)}<button class="share-text" id="shareApp" type="button">Share</button></div><section class="detail-metrics"><div class="detail-metric"><strong>${esc(a.rating||'New')}</strong><span>Rating</span></div><div class="detail-metric"><strong>v${esc(a.version)}</strong><span>Version</span></div><div class="detail-metric"><strong>${a.comingSoon?'—':esc(a.size)}</strong><span>Size</span></div><div class="detail-metric"><strong>${esc(a.updated)}</strong><span>Updated</span></div></section>${shots.length?`<section class="detail-section"><h2>Screenshots</h2><div class="screenshot-strip">${shots.map((s,i)=>previewMarkup(a,s,i)).join('')}</div></section>`:''}<section class="detail-section"><h2>About</h2><p>${esc(a.description)}</p>${features.length?`<div class="feature-grid">${features.map(f=>`<div class="feature-card"><strong>${esc(f.title)}</strong><span>${esc(f.text)}</span></div>`).join('')}</div>`:''}</section>${reviewMarkup(a)}<section class="detail-section"><h2>What's New</h2><div class="whats-new"><strong>Version ${esc(a.version)}</strong><ul>${changes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></section><section class="detail-section"><h2>Information</h2><div class="info-list"><div class="info-row"><strong>Developer</strong><span>${esc(a.developer)}</span></div><div class="info-row"><strong>Category</strong><span>${esc(a.category)}</span></div><div class="info-row"><strong>Android</strong><span>${esc(a.android)}</span></div><div class="info-row"><strong>Price</strong><span>${esc(a.price)}</span></div>${a.packageName?`<div class="info-row"><strong>Package</strong><span>${esc(a.packageName)}</span></div>`:''}</div></section>`;hydratePreviews();bindDetail(a);loadReviews(a)}
async function hydratePreviews(){const imgs=[...root.querySelectorAll('[data-preview-src]')];await Promise.all(imgs.map(async img=>{const path=img.dataset.previewSrc;try{let src=path;if(path.endsWith('.b64')){const r=await fetch(`${path}?v=${DATA_V}`,{cache:'no-store'});if(!r.ok)throw new Error();const b64=(await r.text()).trim().replace(/\s+/g,'');const mime=b64.startsWith('/9j/')?'image/jpeg':b64.startsWith('iVBOR')?'image/png':b64.startsWith('UklGR')?'image/webp':null;if(!mime)throw new Error();src=`data:${mime};base64,${b64}`}img.src=src;await img.decode();img.addEventListener('click',()=>openImage(src))}catch{img.remove()}}))}
function reviewText(body=''){return body.replace(/\*\*/g,'').replace(/^\s*Rating\s*:\s*[^\n]+\n?/im,'').replace(/^\s*Review\s*:\s*/im,'').replace(/\r/g,'').trim()}
function reviewRating(body=''){const m=body.match(/Rating[^0-9]*([1-5](?:\.\d)?)/i);return m?Math.max(1,Math.min(5,Math.round(Number(m[1])))):5}
async function loadReviews(a){const issue=reviewIssues[a.slug],target=document.querySelector('#reviewList');if(!issue||!target)return;try{const r=await fetch(`https://api.github.com/repos/${REVIEW_REPO}/issues/${issue}/comments?per_page=20`,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error();const comments=(await r.json()).filter(c=>c.body&&c.user).slice(-4).reverse();if(!comments.length){target.innerHTML='<div class="review-empty"><strong>No public reviews yet</strong>Use “Write a Review” to add the first real user review.</div>';return}target.innerHTML=comments.map(c=>{const body=reviewText(c.body),rating=reviewRating(c.body),date=new Date(c.created_at).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});return `<article class="review-card"><div class="review-top"><img class="review-avatar" src="${esc(c.user.avatar_url)}" alt=""><div class="review-person"><strong>${esc(c.user.login)}</strong><span class="review-date">${esc(date)}</span></div><span class="review-stars" aria-label="${rating} out of 5 stars">${stars(rating)}</span></div><p class="review-body">${esc(body||'Shared a rating for this app.')}</p><a class="review-link" href="${esc(c.html_url)}" target="_blank" rel="noopener">View on GitHub</a></article>`}).join('')}catch{target.innerHTML='<div class="review-empty"><strong>Public reviews are temporarily unavailable</strong>The store samples below are still visible.</div>'}}
function toast(msg){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)}el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}
function bindDetail(a){document.querySelector('[data-detail-install]')?.addEventListener('click',()=>rememberInstall(a));document.querySelector('#shareApp')?.addEventListener('click',async()=>{const data={title:a.name,text:a.shortDescription,url:canonicalUrl(a)};try{if(navigator.share){await navigator.share(data);return}await navigator.clipboard.writeText(data.url);toast('App link copied')}catch{}})}
const dlg=document.querySelector('#imageDialog'),dlgImg=document.querySelector('#dialogImage');function openImage(src){if(!dlg||!dlgImg)return;dlgImg.src=src;dlg.showModal()}document.querySelector('#closeImage')?.addEventListener('click',()=>dlg.close());dlg?.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
Promise.all([fetch(`data/apps.json?v=${DATA_V}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`data/wow-note.json?v=${DATA_V}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()})]).then(([data,note])=>{const a=[...(data.apps||[]),note].find(x=>x.slug===slug);if(!a)throw new Error();render(a)}).catch(()=>root.innerHTML='<div class="loading-card">App not found.<br><br><a href="./#apps">Back to App Store</a></div>');