const $=s=>document.querySelector(s);const grid=$('#appGrid'),search=$('#search'),count=$('#appCount'),featured=$('#featuredApp');let apps=[];
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('wow-store-theme',t);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',t==='dark'?'#11161d':'#f7f8fa')}
setTheme(localStorage.getItem('wow-store-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
$('#themeToggle')?.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const action=(a,cls)=>a.comingSoon?`<span class="${cls} coming-soon" aria-disabled="true">COMING SOON</span>`:`<a class="${cls}" href="${esc(a.apk)}" download>GET</a>`;
const newestFirst=list=>[...list].sort((a,b)=>{const ad=Date.parse(a.updated||'')||0,bd=Date.parse(b.updated||'')||0;return bd-ad});
function renderFeatured(a){if(!featured||!a)return;featured.innerHTML=`<article class="featured-card"><div class="featured-main"><a class="featured-identity" href="app.html?app=${encodeURIComponent(a.slug)}"><img class="featured-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"><span class="featured-copy"><small class="featured-label">FEATURED APP</small><strong>${esc(a.name)}</strong><em>${esc(a.developer)}</em></span></a>${action(a,'install-small')}</div><p class="featured-description">${esc(a.shortDescription)}</p><div class="featured-meta"><span><b>v${esc(a.version)}</b><small>Version</small></span><span><b>${a.comingSoon?'Coming Soon':esc(a.size)}</b><small>Size</small></span><span><b>${esc(a.android)}</b><small>Android</small></span><span><b>${esc(a.price)}</b><small>Price</small></span></div><a class="featured-details" href="app.html?app=${encodeURIComponent(a.slug)}">View app details <span>›</span></a></article>`}
function render(list){count.textContent=`${list.length} ${list.length===1?'app':'apps'}`;grid.innerHTML=list.map(a=>`<article class="app-row"><a class="app-row-link" href="app.html?app=${encodeURIComponent(a.slug)}"><img class="app-row-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"><span class="app-row-copy"><h3>${esc(a.name)}</h3><div class="developer">${esc(a.developer)}</div><p>${esc(a.shortDescription)}</p></span></a><div class="app-row-side">${action(a,'install-small')}<small>${a.comingSoon?'Preview':`v${esc(a.version)}`}</small></div></article>`).join('')||'<div class="loading-card">No apps found.</div>'}
fetch('data/apps.json?v=10').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{apps=newestFirst(data.apps||[]);renderFeatured(apps[0]);render(apps)}).catch(()=>{if(featured)featured.innerHTML='<div class="loading-card">Unable to load featured app.</div>';grid.innerHTML='<div class="loading-card">Unable to load the app catalog.</div>'});
search?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();render(!q?apps:apps.filter(a=>[a.name,a.developer,a.category,a.shortDescription,(a.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)))});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js?v=10').catch(()=>{}));