const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DATA_V='20';
let apps=[];
let activeCategory='All';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const appUrl=a=>`apps/${encodeURIComponent(a.slug)}/`;
const libraryKey='wow-store-library-v1';
function readLibrary(){try{return JSON.parse(localStorage.getItem(libraryKey)||'{}')||{}}catch{return {}}}
function writeLibrary(v){localStorage.setItem(libraryKey,JSON.stringify(v))}
function rememberInstall(a){if(a.comingSoon||!a.apk)return;const lib=readLibrary();lib[a.slug]={version:a.version,at:Date.now(),name:a.name};writeLibrary(lib);renderLibrary();renderUpdates()}
function storedState(a){const item=readLibrary()[a.slug];if(!item)return 'install';if(item.version!==a.version)return 'update';return a.packageName?'open':'install'}
function actionMarkup(a,where='row'){
  const base=where==='hero'?'install-action':'row-action';
  if(a.comingSoon||!a.apk)return `<span class="${base} disabled">Coming Soon</span>`;
  const state=storedState(a);
  if(state==='open')return `<a class="${base}${where==='hero'?'':' primary'}" href="intent://#Intent;package=${encodeURIComponent(a.packageName)};end" data-open-app="${esc(a.slug)}">Open</a>`;
  const label=state==='update'?'Update':'Install';
  return `<a class="${base}${where==='hero'?'':' primary'}" href="${esc(a.apk)}" download data-install="${esc(a.slug)}">${label}</a>`;
}
function newestFirst(list){return [...list].sort((a,b)=>{const d=(Date.parse(b.updated||'')||0)-(Date.parse(a.updated||'')||0);if(d)return d;if(!!a.comingSoon!==!!b.comingSoon)return a.comingSoon?1:-1;return String(a.name).localeCompare(String(b.name))})}
function appRow(a,compact=false){const status=a.comingSoon?'Preview':`${a.category} · v${esc(a.version)}`;return `<article class="app-row${compact?' compact':''}"><a class="app-row-link" href="${appUrl(a)}"><img class="app-row-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"><div class="app-row-copy"><h3>${esc(a.name)}</h3><div class="developer">${esc(a.developer)}</div><div class="app-submeta">${esc(status)}</div></div></a>${actionMarkup(a,'row')}</article>`}
function miniCard(a){return `<article class="mini-app-card"><a href="${appUrl(a)}"><img src="${esc(a.icon)}" alt=""><h3>${esc(a.name)}</h3><p>${esc(a.category)}</p></a><div class="mini-action"><span>v${esc(a.version)}</span>${actionMarkup(a,'mini')}</div></article>`}
function renderFeatured(){const target=$('#featuredApp');if(!target||!apps.length)return;const a=apps.find(x=>!x.comingSoon)||apps[0];target.innerHTML=`<article class="featured-card"><span class="featured-kicker">FEATURED APP</span><div class="featured-top"><a href="${appUrl(a)}"><img class="featured-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"></a><div class="featured-copy"><a href="${appUrl(a)}"><h2>${esc(a.name)}</h2></a><p>${esc(a.developer)}</p></div></div><p class="featured-desc">${esc(a.shortDescription)}</p><div class="featured-bottom"><div class="featured-meta"><span><b>${esc(a.rating||'New')}</b> rating</span><span><b>v${esc(a.version)}</b></span></div>${actionMarkup(a,'hero')}</div></article>`}
function categories(){return ['All',...new Set(apps.map(a=>a.category).filter(Boolean))]}
function renderCategories(){const home=$('#categoryChips'),filters=$('#searchCategories'),cats=categories();if(home)home.innerHTML=cats.filter(x=>x!=='All').map(c=>`<button class="category-chip" data-home-category="${esc(c)}"><span class="dot"></span>${esc(c)}</button>`).join('');if(filters)filters.innerHTML=cats.map(c=>`<button class="filter-chip${c===activeCategory?' is-active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}
function renderHomeLists(){$('#newApps').innerHTML=apps.slice(0,5).map(miniCard).join('');$('#recentApps').innerHTML=apps.slice(0,4).map(a=>appRow(a,true)).join('')}
function filteredApps(){const q=($('#search')?.value||'').trim().toLowerCase();return apps.filter(a=>{const inCat=activeCategory==='All'||a.category===activeCategory;if(!inCat)return false;if(!q)return true;const hay=[a.name,a.developer,a.category,a.shortDescription,(a.tags||[]).join(' ')].join(' ').toLowerCase();return hay.includes(q)})}
function renderCatalog(){const list=filteredApps();$('#appCount').textContent=`${list.length} ${list.length===1?'app':'apps'}`;$('#appGrid').innerHTML=list.map(appRow).join('')||'<div class="empty-state">No apps found. Try another search or category.</div>'}
function renderUpdates(){const lib=readLibrary();const updates=apps.filter(a=>lib[a.slug]&&!a.comingSoon&&lib[a.slug].version!==a.version);$('#availableUpdates').innerHTML=updates.length?updates.map(appRow).join(''):'<div class="empty-state">You’re up to date. New versions will appear here when available.</div>';$('#updatesRecent').innerHTML=apps.slice(0,6).map(appRow).join('')}
function renderLibrary(){const lib=readLibrary();const list=apps.filter(a=>lib[a.slug]).sort((a,b)=>(lib[b.slug]?.at||0)-(lib[a.slug]?.at||0));$('#libraryApps').innerHTML=list.length?list.map(appRow).join(''):'<div class="empty-state">No apps in your library yet.<br>Install an app from Home or Apps and it will appear here.</div>'}
function route(){const screen=['home','apps','updates','library'].includes(location.hash.slice(1))?location.hash.slice(1):'home';$$('.screen').forEach(el=>el.classList.toggle('is-active',el.dataset.screen===screen));$$('[data-nav]').forEach(el=>el.classList.toggle('is-active',el.dataset.nav===screen));const titles={home:'App Store',apps:'Apps & Search',updates:'Updates',library:'Library'};$('#screenTitle').textContent=titles[screen];if(screen==='updates')renderUpdates();if(screen==='library')renderLibrary();window.scrollTo({top:0,behavior:'auto'})}
function bindEvents(){window.addEventListener('hashchange',route);$('#search')?.addEventListener('input',renderCatalog);document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]');if(cat){activeCategory=cat.dataset.category;renderCategories();renderCatalog();return}const homeCat=e.target.closest('[data-home-category]');if(homeCat){activeCategory=homeCat.dataset.homeCategory;renderCategories();renderCatalog();location.hash='apps';return}const install=e.target.closest('[data-install]');if(install){const a=apps.find(x=>x.slug===install.dataset.install);if(a)rememberInstall(a)}})}
Promise.all([fetch(`data/apps.json?v=${DATA_V}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}),fetch(`data/wow-note.json?v=${DATA_V}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()})]).then(([data,wowNote])=>{apps=newestFirst([...(data.apps||[]),wowNote]);renderFeatured();renderCategories();renderHomeLists();renderCatalog();renderUpdates();renderLibrary();bindEvents();route()}).catch(()=>{$('#featuredApp').innerHTML='<div class="empty-state">Unable to load the app catalog.</div>';$('#appGrid').innerHTML='<div class="empty-state">Unable to load apps. Please reload.</div>'});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register(`sw.js?v=${DATA_V}`).catch(()=>{}));