const $=s=>document.querySelector(s);const grid=$('#appGrid'),search=$('#search'),count=$('#appCount'),featured=$('#featuredApp');let apps=[];
function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('wow-store-theme',t);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',t==='dark'?'#0f141b':'#f6f7f9')}
const saved=localStorage.getItem('wow-store-theme');setTheme(saved||((matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'));
$('#themeToggle')?.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderFeatured(a){if(!a)return;const shot=(a.screenshots||[])[1]||(a.screenshots||[])[0]||a.icon;featured.innerHTML=`<article class="featured-card"><a class="featured-image" href="app.html?app=${encodeURIComponent(a.slug)}"><img src="${esc(shot)}" alt="${esc(a.name)} preview"><div class="featured-copy"><span class="featured-label">FEATURED</span><h2>${esc(a.name)}</h2><p>${esc(a.shortDescription)}</p></div></a><div class="featured-actions"><div class="featured-meta"><span><b>v${esc(a.version)}</b> version</span><span><b>${esc(a.size)}</b> size</span><span><b>${esc(a.price)}</b></span></div><a class="install-small" href="${esc(a.apk)}" download>GET</a></div></article>`}
function render(list){count.textContent=`${list.length} ${list.length===1?'app':'apps'}`;grid.innerHTML=list.map(a=>`<article class="app-row"><a href="app.html?app=${encodeURIComponent(a.slug)}"><img class="app-row-icon" src="${esc(a.icon)}" alt="${esc(a.name)} icon"></a><a href="app.html?app=${encodeURIComponent(a.slug)}"><h3>${esc(a.name)}</h3><div class="developer">${esc(a.developer)}</div><p>${esc(a.shortDescription)}</p></a><div class="app-row-side"><a class="install-small" href="${esc(a.apk)}" download>GET</a><small>v${esc(a.version)}</small></div></article>`).join('')||'<div class="loading-card">No apps found.</div>'}
fetch('data/apps.json').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{apps=data.apps||[];renderFeatured(apps[0]);render(apps)}).catch(()=>{grid.innerHTML='<div class="loading-card">Unable to load the app catalog.</div>'});
search?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();render(!q?apps:apps.filter(a=>[a.name,a.developer,a.category,a.shortDescription,(a.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)))});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));